const List<String> ibadatTypes = [
  'Salah',
  'Sawm',
  'Qiyyam',
  'Quran',
  'Sadaqat',
];

const List<Map<String, String>> quranVerses = [
  {
    'verse': 'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    'translation': 'Indeed, Allah is with the patient.',
  },
  {
    'verse': 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
    'translation': 'So remember Me; I will remember you. And be grateful to Me and do not deny Me.',
  },
  {
    'verse': 'وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا',
    'translation': 'And those who strive for Us - We will surely guide them to Our ways.',
  },
  {
    'verse': 'وَمَنْ أَعْرَضَ عَن ذِكْرِي فَإِنَّ لَهُ مَعِيشَةً ضَنكًا',
    'translation': 'And whoever turns away from My remembrance - indeed, he will have a depressed life.',
  },
  {
    'verse': 'لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا',
    'translation': 'He created death and life to test you as to which of you is best in deed.',
  },
  {
    'verse': 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
    'translation': 'For indeed, with hardship comes ease.',
  },
  {
    'verse': 'إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ وَيُحِبُّ الْمُتَطَهِّرِينَ',
    'translation': 'Indeed, Allah loves those who are constantly repentant and loves those who purify themselves.',
  },
  {
    'verse': 'وَقُل رَّبِّ زِدْنِي عِلْمًا',
    'translation': 'And say, "My Lord, increase me in knowledge."',
  },
  {
    'verse': 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا',
    'translation': 'For indeed, with hardship comes ease.',
  },
  {
    'verse': 'إِنَّ فِي ذَٰلِكَ لَذِكْرَىٰ لِمَن كَانَ لَهُ قَلْبٌ',
    'translation': 'Indeed in that is a reminder for whoever has a heart.',
  },
];

const List<String> quranSurahList = [
  'Al-Fatihah',
  'Al-Baqarah',
  'Aal-Imran',
  'An-Nisa',
  'Al-Ma\'idah',
  'Al-An\'am',
  'Al-A\'raf',
  'Al-Anfal',
  'At-Tawbah',
  'Yunus',
  'Hud',
  'Yusuf',
  'Ar-Ra\'d',
  'Ibrahim',
  'Al-Hijr',
  'An-Nahl',
  'Al-Isra',
  'Al-Kahf',
  'Maryam',
  'Taha',
  'Al-Anbiya',
  'Al-Hajj',
  'Al-Mu\'minun',
  'An-Nur',
  'Al-Furqan',
  'Ash-Shu\'ara',
  'An-Naml',
  'Al-Qasas',
  'Al-Ankabut',
  'Ar-Rum',
  'Luqman',
  'As-Sajdah',
  'Al-Ahzab',
  'Saba',
  'Fatir',
  'Yasin',
  'As-Saffat',
  'Sad',
  'Az-Zumar',
  'Ghafir',
  'Fussilat',
  'Ash-Shura',
  'Az-Zukhruf',
  'Ad-Dukhan',
  'Al-Jathiyah',
  'Al-Ahqaf',
  'Muhammad',
  'Al-Fath',
  'Al-Hujurat',
  'Qaf',
  'Adh-Dhariyat',
  'At-Tur',
  'An-Najm',
  'Al-Qamar',
  'Ar-Rahman',
  'Al-Waqi\'ah',
  'Al-Hadid',
  'Al-Mujadilah',
  'Al-Hashr',
  'Al-Mumtahanah',
  'As-Saff',
  'Al-Jumu\'ah',
  'Al-Munafiqun',
  'At-Taghabun',
  'At-Talaq',
  'At-Tahrim',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Haqqah',
  'Al-Ma\'arij',
  'Nuh',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddathir',
  'Al-Qiyamah',
  'Al-Insan',
  'Al-Mursalat',
  'An-Naba',
  'An-Nazi\'at',
  'Abasa',
  'At-Takwir',
  'Al-Infitar',
  'Al-Mutaffifin',
  'Al-Inshiqaq',
  'Al-Buruj',
  'At-Tariq',
  'Al-A\'la',
  'Al-Ghashiyah',
  'Al-Fajr',
  'Al-Balad',
  'Ash-Shams',
  'Al-Layl',
  'Ad-Duha',
  'Ash-Sharh',
  'At-Tin',
  'Al-Alaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-Adiyat',
  'Al-Qari\'ah',
  'At-Takathur',
  'Al-Asr',
  'Al-Humazah',
  'Al-Fil',
  'Quraysh',
  'Al-Ma\'un',
  'Al-Kawthar',
  'Al-Kafirun',
  'An-Nasr',
  'Al-Masad',
  'Al-Ikhlas',
  'Al-Falaq',
  'An-Nas',
];